# Site settings
title: Paul Jo
header-img: img/home-bg.jpg
email: dev.pauljo@gmail.com
copyright_name: Paul Jo · All right reserved.
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://pauljo.github.io"
twitter_username: jbw_kor
github_username:  pauljo
facebook_username:  pauljo1993
email_username:  dev.pauljo@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id: UA-79246361-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
